spring.application.name=f1-race-explorer

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/f1_race_explorer
spring.datasource.username=postgres
spring.datasource.password=GodLovesRomeiro11
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin

# JWT Configuration
app.jwt.secret=your_jwt_secret_key_here_which_should_be_at_least_256_bits
app.jwt.expiration=86400000

# Server Configuration
server.port=8080
